
import '../../api/promotions/methods'
import '../../api/categories/methods'
import '../../api/banners/methods'
import '../../api/items/methods'
import '../../api/carts/methods'
import '../../api/invoices/methods'
import '../../api/webSettings/methods'
import '../../api/tasks/methods'
import '../../api/tasks/publication'
import '../../api/users/methods'
import '../../api/users/publication'
import '../../api/data/regencies'